

export const Locators = {
    demoQaUrl: "https://demoqa.com",
    userFullName: "//input[@id='userName']",
    userFirstName: "//input[@id='firstName']",
    userLastName: "//input[@id='lastName']",
    userEmail: "//input[@id='userEmail']",
    userMobileNumber: "//input[@id='userNumber']",
    userDateBirth: "//input[@id='dateOfBirthInput']",
    userAge: "//input[@id='age']",
    userSalary: "//input[@id='salary']",
    userHobbiesRead: "//input[@id='hobbies-checkbox-2']",
    userDepartment: "//input[@id='department']",
    userCurrentAddress: "//textarea[@id='currentAddress']",
    userPermanentAddress: "//textarea[@id='permanentAddress']",
    genderRadioButton: "//input[@id='gender-radio-1']",
    impressiveLabel: "//label[@for='impressiveRadio']",
    greatLabelForm: "//div[contains(@class, 'card-body')]/h5[text()='Forms']",
    practiceFormLabel: "//span[text()='Practice Form']",
    submitButton: "//button[@id='submit']",
    greatLabelAlerts: "//div[@class='header-text' and contains(., 'Alerts, Frame & Windows')]",
    alertsLabel: "//span[text()='Alerts']",
    firstAlertButton: "//button[@id='alertButton']",
    timerAlertButton: "//button[@id='timerAlertButton']",
    confirmAlertButton: "//button[@id='confirmButton']",
    promptAlertButton: "//button[@id='promtButton']",
    greatLabelElements: "(//div[@class='card mt-4 top-card'])[1]",
    textBoxButton: "//li[@class='btn btn-light ' and contains(., 'Text Box')]",
    checkBoxLabel: "//li[@class='btn btn-light ' and contains(., 'Check Box')]",
    checkBoxCircle: "//span[@class='rct-checkbox']",
    radioButton: "//li[@class='btn btn-light ' and contains(., 'Radio Button')]",
    greatLabelWebTables: "//li[@class='btn btn-light ' and contains(., 'Web Tables')]",
    newRecordButton: "//button[@id='addNewRecordButton']",
    editRecordButton: "(//span[@title='Edit'])[4]",
    deleteRecordButton: "(//span[@title='Delete'])[4]",

}